name: Quality Check

on:
  push:
  pull_request:

jobs:
  test:
    name: Test and coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: go test
        run: |
          go test -v -race \
            -timeout 2m -p 1 \
            -covermode=atomic \
            -coverprofile=coverage.txt \
            ./...

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  vet:
    name: go vet and lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          go get -u golang.org/x/lint/golint

      - name: go vet
        run: go vet ./...

      - name: go lint
        run: golint -set_exit_status ./...

  golangci:
    name: golangci lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43.0
